"""add client portal fields

Revision ID: 064b9b845972
Revises: 11f7b0c5e5f5
Create Date: 2026-07-22 15:54:30.191105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064b9b845972'
down_revision = '11f7b0c5e5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_visible', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_client_id_clients', 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_client_id_clients', type_='foreignkey')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('client_visible')

    # ### end Alembic commands ###
