"""add user is_archived field

Revision ID: 50faf190031d
Revises: 064b9b845972
Create Date: 2026-07-23 10:13:53.376737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50faf190031d'
down_revision = '064b9b845972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
