"""add deadline revision approval workflow

Revision ID: fb82866dcd63
Revises: d6fdc9c8e7d6
Create Date: 2026-07-22 15:00:10.454556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb82866dcd63'
down_revision = 'd6fdc9c8e7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deadline_revisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='approved'))
        batch_op.add_column(sa.Column('decision_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('decided_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deadline_revisions', schema=None) as batch_op:
        batch_op.drop_column('decided_at')
        batch_op.drop_column('decision_notes')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
